version: "3.8"

services:
  nginx-rtmp:
    container_name: nginx-rtmp
    image: tiangolo/nginx-rtmp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1935:1935
      - 8080:8080
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m

  rtmp-auth:
    container_name: rtmp-auth
    image: ubuntu
    command: /go-gin-auth
    volumes:
      - ./go-gin-auth:/go-gin-auth
    ports:
      - "8080"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
